config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/all-requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'

  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'


  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'


  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create] 
  end

  resources :requests

  devise_for :users, 
              path: '', 
              path_names:{sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers:{omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :gigs
  has_many :requests
  has_many :offers

  
  has_many :buying_orders, foreign_key: "buyer_id", class_name: "Order"
  has_many :selling_orders, foreign_key: "seller_id", class_name: "Order"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  validates :full_name, presence: true, length: {maximum: 50}

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      if !user.provider
        user.update(uid: auth.uid, provider: auth.provider, image: auth.info.image)
      end
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.full_name = auth.info.name
        user.image = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider

      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def dashboard
  end

  def show
    @user = User.find(params[:id])
    
  end

  def update
    @user = current_user
    if @user.update_attributes(current_user_params)
      flash[:notice] = "Saved..."
    else
      flash[:alert] = "Cannot update..."
    end
    redirect_to dashboard_path
  end

  private
  def current_user_params
    params.require(:user).permit(:from, :about, :status, :language, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/dashboard.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
        
            <!-- LEFT SIDE -->
            <div class="column is-one-third">
                <div class="columns is-multiline">

                    <!-- Top Card -->
                    <div class="column is-full">
                        <div class="card">

                            <!-- Avatar -->
                            <div class="card-content is-horizontal-center is-flex">
                            <figure class='image is-128x128'>
                                <%= image_tag avatar_url(current_user), class: 'is-rounded' %>
                            </figure>
                            </div>
                            
                            <div class="card-content">

                                <!-- Upload Button -->
                                <div class="content has-text-centered">
                                    <p class="title is-5"><%= current_user.full_name %></p>
                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post do |f| %>
                                      <div class="file">
                                        <label class="button is-primary is-outline is-fullwidth">
                                         <%= f.file_field :avatar, class: "file-input", onchange: "this.form.submit();" %>
                                         <i class="fas fa-upload"></i>&nbsp;&nbsp;&nbsp;Upload Avatar
                                        </label>
                                      </div>
                                    <% end %>
                                </div>
                                <hr class="h-10">
                                
                                <!-- Member -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">Member Since</div>
                                        <div class="media-right">
                                            <strong><%= current_user.created_at.strftime('%b %y')%></strong>
                                        </div>
                                    </div>
                                </article>
                                <hr class="h-10">
                                
                                <!-- From -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">From</div>
                                        <div class="media-right">
                                            <strong><%= current_user.from %></strong> <i class="toggle far fa-edit" aria-controls="user-from"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                    <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id:'user-from', class:'is-hidden'} do |f| %>
                                      <div class="field">
                                        <%= f.text_field :from, autofocus: true, autocomplete: 'form', class:'input'%>
                                      </div>
                                      <a class="toggle button is-light" aria-controls="user-form">Cancel</a>
                                      <%= f.submit "Save", class:'button is-danger' %>
                                    <% end %>
                                    </div>
                                </article>                                
                                <hr class="h-10">

                                <!-- Online Status -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">Online Status</div>
                                        <div class="media-right">
                                            <strong><% if current_user.status %> Online <%else%> Offline <%end%></strong> <i class="toggle far fa-edit" aria-controls="user-status"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id:'user-status', class:'is-hidden'} do |f| %>
                                        <div class="field">
                                            <%= f.select(:status, options_for_select([["Online", true],["Offline", false]]),{}, {class:"select is-fullwidth"})%>
                                        </div>
                                        <a class="toggle button is-light" aria-controls="user-form">Cancel</a>
                                        <%= f.submit "Save", class:'button is-danger' %>
                                        <% end %>
                                    </div>
                                </article>

                            </div>
                        </div>
                    </div>

                    <!-- Bottom Card -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">

                                <!-- About -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">
                                            <p>
                                                <strong>About Yourself</strong>
                                                <br>
                                                <%= current_user.about %>
                                            </p>
                                        </div>
                                        <div class="media-right">
                                            <i class="toggle far fa-edit" aria-controls="user-about"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id:'user-about', class:'is-hidden'} do |f| %>
                                        <div class="field">
                                            <%= f.text_area :about, autofocus: true, autocomplete: 'form', class:'input'%>
                                        </div>
                                        <a class="toggle button is-light" aria-controls="user-about">Cancel</a>
                                        <%= f.submit "Save", class:'button is-danger' %>
                                        <% end %>
                                    </div>
                                </article>
                                <hr class="h-10">

                                <!-- Languages -->
                                <article>
                                     <div class="media">
                                        <div class="media-content">
                                            <p>
                                                <strong>Language</strong>
                                                <br>
                                                <%= current_user.about %>
                                            </p>
                                        </div>
                                        <div class="media-right">
                                            <i class="toggle far fa-edit" aria-controls="user-language"></i>
                                        </div>
                                    </div>

                                    <div class="content">
                                        <%= form_for :user, url: users_edit_url(@user), action: :update, method: :post, html: {id:'user-about', class:'is-hidden'} do |f| %>
                                        <div class="field">
                                            <%= f.text_field :langauge, autofocus: true, autocomplete: 'form', class:'input'%>
                                        </div>
                                        <a class="toggle button is-light" aria-controls="user-language">Cancel</a>
                                        <%= f.submit "Save", class:'button is-danger' %>
                                        <% end %>
                                    </div>
                                </article>
                                <hr class="h-10">
                                
                                <!-- Linked Account -->
                                <article class="media">
                                    <div class="content">
                                        <p>
                                            <strong>Linked Account</strong>
                                            <% if current_user.uid? %>
                                                <span class="has-text-success">
                                                Facebook Verified
                                                </span>
                                            <%else%>
                                                <%= link_to 'Connect to Facebook', user_facebook_omniauth_authorize_path, class:'has-text-danger' %>
                                            <%end%>
                                        </p>
                                    </div>
                                </article>

                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="columns is-multiline">

                    <!-- Create New Gig -->
                    <div class="column is-one-third has-text-centered">
                        <%= link_to new_gig_path do %>
                        <div class="card">

                            <div class="card-image card-content is-horizontal-center is-flex ">
                                <figure class="image is-128x128 ">
                                    <%= image_tag 'icon_add.png' %>
                                </figure>
                            </div>

                            <div class="card-content">
                                <strong>Create New Gig</strong>
                            </div>    

                        </div>
                        <%end%>
                    </div>

                     <!-- Display Gigs -->
                    <% current_user.gigs.each do |gig| %>

                        <div class="column is-one-third">
                            <div class="card">

                                <div class="card-image">
                                    <%= link_to edit_gig_path(gig) do %>
                                        <figure class="image is-4by3">
                                            <%= image_tag gig_cover(gig) %>
                                        </figure>
                                    <% end %>
                                </div>

                                <div class="card-content p-t-5 p-b-5">
                                    <p class="subtitle is-6 m-b-5"><%= link_to gig.title, gig_path(gig) %></p>
                                    <span class="star-review"><i class="fa fa-star"></i>
                                        4.8 <span class="has-text-primary">(23)</span>
                                    </span>                                        
                                </div>

                                <footer class="card-footer">
                                    <% basic_price = gig.pricings.find{ |p| p.pricing_type == 'basic' } %>

                                    <a class="has-text-danger is-block card-footer-item has-text-right">
                                        <% if !basic_price.nil? %>
                                            <span class="small-title">STARTING AT</span> 
                                            <strong>£<%= basic_price.price %></strong>                                            
                                        <% else %>
                                            <strong>
                                                <span class="small-title has-text-dark">NO PRICING YET</span>
                                            </strong>
                                        <% end %>
                                    </a>
                                </footer>  
                                
                            </div>
                        </div>

                    <% end %>
                    
                </div>
            </div>
            
        </div>
    </div>
</section>

app/views/users/show.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
        
            <!-- LEFT SIDE -->
            <div class="column is-one-third">
                <div class="columns is-multiline">

                    <!-- Top Card -->
                    <div class="column is-full">
                        <div class="card">

                            <!-- Avatar -->
                            <div class="card-content is-horizontal-center is-flex">
                            <figure class='image is-128x128'>
                                <%= image_tag avatar_url(@user), class: 'is-rounded' %>
                            </figure>
                            </div>
                            
                            <div class="card-content">

                                <!-- Upload Button -->
                                <div class="content has-text-centered">
                                    <p class="title is-5"><%= @user.full_name %></p>
                                </div>
                                <hr class="h-10">
                                
                                <!-- Member -->
                                <article>
                                    <div class="media">
                                        <div class="media-content">Member Since</div>
                                        <div class="media-right">
                                            <strong><%= @user.created_at.strftime('%b %y')%></strong>
                                        </div>
                                    </div>
                                </article>
                                <hr class="h-10">
                                
                                <!-- From -->
                                <article class="media">
                                        <div class="media-content">From</div>
                                        <div class="media-right">
                                            <strong><%= @user.from %></strong> <i class="toggle far fa-edit" aria-controls="user-from"></i>
                                        </div>
                                </article>                                
                                <hr class="h-10">

                                <!-- Online Status -->
                                <article class="media">
                                        <div class="media-content">Online Status</div>
                                        <div class="media-right">
                                            <strong><% if @user.status %> Online <%else%> Offline <%end%></strong> <i class="toggle far fa-edit" aria-controls="user-status"></i>
                                        </div>
                                </article>

                            </div>
                        </div>
                    </div>

                    <!-- Bottom Card -->
                    <div class="column is-full">
                        <div class="card">
                            <div class="card-content">

                                <!-- About -->
                                <article class="media">
                                        <div class="media-content">
                                            <p>
                                                <strong>About Yourself</strong>
                                                <br>
                                                <%= @user.about %>
                                            </p>
                                        </div>
                                </article>
                                <hr class="h-10">

                                <!-- Languages -->
                                <article class="media">
                                        <div class="media-content">
                                            <p>
                                                <strong>Language</strong>
                                                <br>
                                                <%= @user.about %>
                                            </p>
                                        </div>
                                </article>
                                <hr class="h-10">
                                
                                <!-- Linked Account -->
                                <article class="media">
                                    <div class="content">
                                        <p>
                                            <strong>Linked Account</strong>
                                            </br>
                                            <% if @user.uid? %>
                                                <span class="has-text-success">
                                                Facebook Verified
                                                </span>
                                            <%else%>
                                                <span class="has-text-danger">
                                                Facebook Unverified
                                                </span>                                            <%end%>
                                        </p>
                                    </div>
                                </article>

                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <!-- RIGHT SIDE -->
            <div class="column">
                <div class="card">
                    
                    <div class="card-header">
                        <div class="card-header-title">
                            Latest Reviews
                        </div>
                    </div>
                    
                    <div class="card-content">
                        <article class="media">
                            <figure class='media-left'>
                                <p class="image is-64x64">
                                <%= image_tag avatar_url(@user), class: 'is-rounded' %>
                                </p>
                            </figure>

                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <strong>John Smith</strong>
                                        <br/>
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur vero tempora optio cumque beatae, architecto velit vel reiciendis similique itaque asperiores ipsa quaerat deserunt? Modi quibusdam sint totam facilis cumque!
                                    </p>
                                    <small>31m</small>
                                </div>
                            </div>

                             <div class="media-right">
                                <span class="star-review"><i class="fa fa-star"></i>5.0</span>
                            </div>
                            
                        </article>
                        
                        

                       

                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>