config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/all-requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'

  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'


  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'


  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create] 
  end

  resources :requests

  devise_for :users, 
              path: '', 
              path_names:{sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers:{omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_categories.html.erb
<nav class="navbar has-shadow" style="z-index:5">
    <div class="container">
        <div class="navbar">
            <% @categories.each do |category| %>
              <%= link_to "#{category.name}", root_path, class:"navbar-item" %>
            <% end %>
        </div>
    </div>
</nav>

app/views/shared/_navbar.html.erb
    <nav class="navbar is-warning" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="/">
           <h1>Freelancer</h1>
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
         <div class="navbar-item">
            <div class="field has-addons">
                <div class="control">
                    <input class="input" type="text" placeholder="Find a service">
                </div>
                <div class="control">
                    <a class="button is-danger">Search</a>
                </div>
            </div>
         </div>
        </div>

        <div class="navbar-end">
          <%= link_to ' Add New Gig', new_gig_path, class: 'navbar-item' %>
          <a href="/" class="navbar-item">Browse gig</a>

          <% if(!user_signed_in?) %>
          <div class="navbar-item">
            <div class="buttons">
              <%= link_to 'Sign Up', new_user_registration_path, class:'button is-primary' %>
              <%= link_to 'Log In', new_user_session_path, class:'button is-light' %>
            </div>
          </div>
          <% else %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <figure class='image is-24x24 m-r-5'>
                <%= image_tag avatar_url(current_user), class: 'is-rounded' %>
                
              </figure>
              <%= current_user.full_name %>
            </a>
            <div class="navbar-dropdown">
              <%= link_to 'Profile', edit_user_registration_path, class:'navbar-item' %>
              <%= link_to 'Dashboard', dashboard_path, class:'navbar-item' %>
              <hr class="navbar-divider">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:'navbar-item' %>

            </div>
          </div>
          <% end %>
        </div>

      </div>
    </nav>

  <% if (user_signed_in?) && !current_page?(root_path) && !current_page?("/gigs/#{params[:id]}") && !current_page?("/users/#{params[:id]}") %>
     <nav class='navbar has-shadow' style="z-index: 5">
      <div class="container">
        <div class="navbar">
          <%= link_to 'Dashboard', dashboard_path, class:'navbar-item' %>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Selling</a>
            <div class="navbar-dropdown">
              <%= link_to 'Add New Gig', new_gig_path, class: 'navbar-item' %>
            </div>
          </div>

           <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Buying</a>
            <div class="navbar-dropdown">
              <%= link_to 'Post Request', new_request_path, class: "navbar-item" %>
              <%= link_to 'Manage Request', requests_path, class: "navbar-item" %>
            </div>
          </div>
           
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Buyer Requests</a>
            <div class="navbar-dropdown">
              <%= link_to 'Active Requests', all_requests_path, class: "navbar-item" %>
              <%= link_to 'Offers Sent', my_offers_path, class: "navbar-item" %>
            </div>
          </div>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Orders</a>
            <div class="navbar-dropdown">
              <%= link_to 'Selling Orders', selling_orders_path, class:"navbar-item" %>
              <%= link_to 'Buying Orders', buying_orders_path, class:"navbar-item" %>
            </div>
          </div>
          <%= link_to 'Earnings', dashboard_path, class:'navbar-item' %>
          <%= link_to 'Messages', dashboard_path, class:'navbar-item' %>
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Settings</a>
            <div class="navbar-dropdown">
              <a class="navbar-item">Payment Method</a>
              <a class="navbar-item">Payout Method</a>
            </div>
          </div>
          
        </div>
      </div>
    </nav>
  <% end %>

   


<script>
  $(document).ready(function() {

    // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        $(".navbar-burger").toggleClass("is-active");
        $(".navbar-menu").toggleClass("is-active");

    });
  });
</script>

app/views/shared/_notification.html.erb
<% unless flash.empty? %>
  <script>
    <% flash.each do |key,value| %>
      <% type = key.to_str.gsub('alert', 'error').gsub('notice', 'success') %>
      new Noty ({
          type: '<%= type %>',
          layout: 'topRight',
          timeout: '3000',
          theme: 'sunset',
          text: '<%= value %>'
      }).show();
    <% end %>
  </script>
<% end %>