config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get '/dashboard', to: 'users#dashboard'
  get '/users/:id', to: 'users#show'
  get '/selling_orders', to: 'orders#selling_orders'
  get '/buying_orders', to: 'orders#buying_orders'
  get '/all-requests', to: 'requests#list'
  get '/request_offers/:id', to: 'requests#offers', as: 'request_offers'
  get '/my_offers', to: 'requests#my_offers'

  post '/users/edit', to: 'users#update'
  post '/offers', to: 'offers#create'
  post '/reviews', to: 'reviews#create'


  put '/orders/:id/complete', to: 'orders#complete', as: 'complete_order'
  put '/offers/:id/accept', to: 'offers#accept', as: 'accept_offer'
  put '/offers/:id/reject', to: 'offers#reject', as: 'reject_offer'


  resources :gigs do
    member do
      delete :delete_photo
      post :upload_photo
    end
    resources :orders, only: [:create] 
  end

  resources :requests

  devise_for :users, 
              path: '', 
              path_names:{sign_up: 'register', sign_in: 'login', edit: 'profile', sign_out: 'logout'},
              controllers:{omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :gig, required: false
  belongs_to :request, required: false

  belongs_to :buyer, class_name: "User"
  belongs_to :seller, class_name: "User"

  has_many :reviews
  

  enum status: [:inprogress, :completed]
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :authenticate_user!
    def create
        gig  = Gig.find(params[:gig_id])
        pricing = gig.pricings.find_by(pricing_type: params[:pricing_type])

        if (pricing && !gig.has_single_pricing) || (pricing && pricing.basic? && gig.has_single_pricing)
            charge(gig, pricing)
        else
            flash[:alert] = "Price is incorrect"
        end
        
        redirect_to request.referrer

    end

    def buying_orders
        @orders = current_user.buying_orders
    end

    def selling_orders
        @orders = current_user.selling_orders
    end

    def complete
        @order = Order.find(params[:id])

        if !@order.completed?
            if @order.completed!
             flash[:notice] = "Saved..."
            else
             flash[:alert] = "Something Went Wrong..."
            end

            redirect_to request.referrer
        end
    end

    private

    def charge(gig, pricing)
        order = gig.orders.new
        order.due_date = Date.today() + pricing.delivery_time.days
        order.title = gig.title
        order.seller_name = gig.user.full_name
        order.seller_id = gig.user.id
        order.buyer_name = current_user.full_name
        order.buyer_id = current_user.id
        order.amount = pricing.price

        if order.save
            flash[:notice] = "Your order has been created..."
        else
            flash[:alert] = order.errors.full_messages.join(', ')
        end

    end
end

app/views/orders/buying_orders.html.erb
<section class="section">
 <div class="container">
    <p class="title">Manage Buying Orders</p>
    <table class="table is-fullwidth">
        <thead>
            <tr>
                <th>Date</th>
                <th>Seller Name</th>
                <th>Title</th>
                <th>Due Date</th>
                <th>Amount</th>
                <th>Status</th>
                <th>Action</th>
                
            </tr>
        </thead>
        <tbody>
        <% if @orders.blank? %>
            <tr>
            <td colspan='7' class="has-text-centered">Nothing to show here.</td>
            </tr>
        <%end%>
            <% @orders.each do |o| %>
                <tr>
                    <td><%= o.created_at.strftime('%d %b %Y')%></td>
                    <td><%= o.seller_name %></td>
                    <td>
                        <%= link_to o.title, gig_path(o.gig) if !o.gig.nil? %>
                        <%= link_to o.title, request_path(o.request) if !o.request.nil? %>
                    </td>
                    <td><%= o.due_date.strftime('%d %b %Y') %></td>
                    <td><%= o.amount %></td>
                    <td>
                        <span class="tag <%= 'is-warning' if o.inprogress? %> <%= 'is-success' if o.completed? %>">
                            <%= o.status.capitalize %>
                        </span>
                    </td>
                    <td>
                        <% if !o.completed? %>
                            <%= link_to 'Mark Complete', complete_order_path(o), method: :put, class: "button is-small is-primary #{'is-hidden' if o.completed?}" %>
                        <% else %>
                            <a class="button is-small is-outlined is-danger toggle-modal" aria-control="<%= o.id %>">Rating</a>

                            <div class="modal" id="<%= o.id %>">
                                    <div class="modal-background"></div>
                                    <div class="modal-content">
                                        <div class="box">
                                            <%= form_for Review.new do |f| %>
                                                <%= f.hidden_field :order_id, value: o.id %>
                                                <div class="field">
                                                    <div id="star_<%= o.id %>"></div>
                                                </div>
                                                <div class="field">
                                                    <%= f.text_area :review, class: "textarea" %>
                                                </div>
                                                <a class="toggle-modal button is-light" aria-control="<%= o.id %>">Cancel</a>

                                              <%= f.submit "Add Review", class:"button is-danger" %>
                                            <% end %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <% end %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
 </div>
</section>

<script>
    $('.toggle-modal').on('click', (e)=>{
        e.stopPropagation();
        e.preventDefault();

        var order_id = e.target.getAttribute('aria-control')
        $('#star_'+order_id).raty({
            path: '/assets/raty-js/lib/images',
            scoreName: 'review[stars]',
            score: 1
        });
         $('#star_'+order_id).raty('reload');
        $('#' + order_id).toggleClass('is-active');
    })
</script>

app/views/orders/selling_orders.html.erb
<section class="section">
 <div class="container">
    <p class="title">Manage Selling Orders</p>
    <table class="table is-fullwidth">
        <thead>
            <tr>
                <th>Date</th>
                <th>Buyer Name</th>
                <th>Title</th>
                <th>Due Date</th>
                <th>Amount</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
        <% if @orders.blank? %>
            <tr>
            <td colspan='6' class="has-text-centered">Nothing to show here.</td>
            </tr>
        <%end%>
            <% @orders.each do |o| %>
                <tr>
                    <td><%= o.created_at.strftime('%d %b %Y')%></td>
                    <td><%= o.buyer_name %>/td>
                    <td>
                        <%= link_to o.title, gig_path(o.gig) if !o.gig.nil? %>
                        <%= link_to o.title, request_path(o.request) if !o.request.nil? %>
                    </td>
                    <td><%= o.due_date.strftime('%d %b %Y') %></td>
                    <td><%= o.amount %></td>
                    <td>
                        <span class="tag <%= 'is-warning' if o.inprogress? %> <%= 'is-success' if o.completed? %>">
                            <%= o.status.capitalize %>
                        </span>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
 </div>
</section>